name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install gcc-arm-linux-gnueabi

    - name: Build
      run: arm-linux-gnueabi-gcc -o chall chall.S
